---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: fetch git submodules
    image: alpine/git
    commands:
    - git submodule init
    - git submodule update --recursive

  - name: yarn
    image: node:14-alpine
    commands:
      - yarn

  - name: yarn lint
    image: node:14-alpine
    commands:
      - yarn lint

  - name: yarn build:dev
    image: node:14-alpine
    commands:
      - yarn build:dev

  - name: run instance crawl
    image: node:14-alpine
    commands:
      # libpq and openssl can probably be removed after lemmy dep is upgraded to 0.16.4+
      - apk add cargo pkgconfig openssl openssl-dev libpq libpq-dev
      - yarn crawl
    when:
      ref:
        - refs/tags/*
      event:
        - cron

  - name: make release build and push to docker hub
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: dessalines/joinlemmy-site
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/tags/*
      event:
        - cron
